# 数据源配置 spring.datasource.druid.odsstage
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://10.2.13.223:3306/hk_graph?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver

    # redis 配置
    redis:
        # 地址
        host: 10.2.13.149
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
        password: User123$
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
